# Moving Average (Média Móvel)

## Importação de bibliotecas

In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

## Importação de dataset

In [4]:
data = pd.read_csv("/content/carne-brasileira-exportada.csv", encoding='utf-8', sep=',')
data.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
0,2014,1,bovino,212.34,8.366,1.951,1.345,2.34,22.57,62.01,4.403
1,2014,2,bovino,212.34,8.516,2.006,1.384,2.22,23.59,61.42,4.729
2,2014,3,bovino,212.34,8.456,2.036,1.547,2.28,19.97,56.50,4.874
3,2014,4,bovino,212.34,8.525,2.058,1.519,2.59,21.46,56.73,4.858
4,2014,1,suino,37.93,8.686,0.747,0.260,2.34,22.57,62.01,2.811

## Separação de dataset por carne

In [5]:
bovino = data[data['tipo_carne'] == 'bovino'].copy()
bovino.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
0,2014,1,bovino,212.34,8.366,1.951,1.345,2.34,22.57,62.01,4.403
1,2014,2,bovino,212.34,8.516,2.006,1.384,2.22,23.59,61.42,4.729
2,2014,3,bovino,212.34,8.456,2.036,1.547,2.28,19.97,56.50,4.874
3,2014,4,bovino,212.34,8.525,2.058,1.519,2.59,21.46,56.73,4.858
12,2015,1,bovino,215.20,7.737,1.836,0.993,2.87,22.95,60.01,4.279

In [6]:
suino = data[data['tipo_carne'] == 'suino'].copy()
suino.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
4,2014,1,suino,37.93,8.686,0.747,0.260,2.34,22.57,62.01,2.811
5,2014,2,suino,37.93,9.151,0.797,0.375,2.22,23.59,61.42,3.471
6,2014,3,suino,37.93,9.640,0.833,0.399,2.28,19.97,56.50,3.774
7,2014,4,suino,37.93,9.494,0.802,0.410,2.59,21.46,56.73,3.674
16,2015,1,suino,40.33,9.170,0.794,0.197,2.87,22.95,60.01,2.589

In [7]:
frango = data[data['tipo_carne'] == 'frango'].copy()
frango.head()

,ano,trimestre,tipo_carne,producao_cabecas_anual_mi,abate_cabecas,peso_carcaca_ton,exportacao_usd,media_cambio_usdbrl,custo_milho_rs,custo_soja_rs,preco_medio_ton_usd
8,2014,1,frango,1331.0,1.395,3.192,1.470,2.34,22.57,62.01,1.779
9,2014,2,frango,1331.0,1.378,3.179,1.764,2.22,23.59,61.42,1.932
10,2014,3,frango,1331.0,1.418,3.249,1.881,2.28,19.97,56.50,1.939
11,2014,4,frango,1331.0,1.406,3.176,1.776,2.59,21.46,56.73,1.891
20,2015,1,frango,1330.0,1.382,3.164,1.354,2.87,22.95,60.01,1.627

### Ordenação temporal

In [8]:
bovino = bovino.sort_values(by=['ano', 'trimestre']).reset_index(drop=True)

In [9]:
suino = suino.sort_values(by=['ano', 'trimestre']).reset_index(drop=True)

In [10]:
frango = frango.sort_values(by=['ano', 'trimestre']).reset_index(drop=True)

## Baseline para bovino

### Simple Moving Average (SMA)

In [11]:
sma = bovino['exportacao_usd'].rolling(window=4).mean()
print(sma)

0         NaN
1         NaN
2         NaN
3     1.44875
4     1.36075
5     1.28825
6     1.21600
7     1.16600
8     1.19125
9     1.19700
10    1.14875
11    1.08375
12    1.08000
13    1.07425
14    1.16700
15    1.26725
16    1.32250
17    1.27100
18    1.34575
19    1.36425
20    1.35350
21    1.46550
22    1.45125
23    1.63225
24    1.72375
25    1.85125
26    1.91375
27    1.86700
28    1.85225
29    1.87825
30    2.14975
31    1.99125
32    2.25425
33    2.51750
34    2.65350
35    2.95325
36    2.79625
37    2.63500
38    2.36600
39    2.37350
40    2.47225
41    2.57175
42    2.73775
43    2.91475
Name: exportacao_usd, dtype: float64

In [12]:
y_true = bovino['exportacao_usd'].iloc[3:]
y_pred = sma.iloc[3:]
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
print(mae, rmse)

0.2547560975609756 0.3443358444607354

### Exponential Moving Average (EMA)

In [13]:
ema = bovino['exportacao_usd'].ewm(span=4, adjust=False).mean()
print(ema)

0     1.345000
1     1.360600
2     1.435160
3     1.468696
4     1.278418
5     1.204651
6     1.225990
7     1.263194
8     1.195517
9     1.164110
10    1.124466
11    1.098280
12    1.090568
13    1.091941
14    1.229564
15    1.321739
16    1.313043
17    1.143026
18    1.379816
19    1.441489
20    1.367694
21    1.355016
22    1.484210
23    1.793726
24    1.725435
25    1.773661
26    1.835397
27    1.929638
28    1.783383
29    1.850030
30    2.315618
31    1.964171
32    2.224902
33    2.536141
34    2.944885
35    2.821331
36    2.487999
37    2.435999
38    2.454399
39    2.539040
40    2.476624
41    2.588374
42    2.811425
43    3.036455
Name: exportacao_usd, dtype: float64

In [14]:
y_true = bovino['exportacao_usd'].iloc[3:]
y_pred = ema.iloc[3:]
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
print(mae, rmse)

0.19315605809784028 0.26274456204523056

## Baseline para suíno

### Simple Moving Average (SMA)

In [15]:
sma = suino['exportacao_usd'].rolling(window=4).mean()
print(sma)

0         NaN
1         NaN
2         NaN
3     0.36100
4     0.34525
5     0.32650
6     0.31850
7     0.29125
8     0.30375
9     0.31025
10    0.31650
11    0.33700
12    0.36650
13    0.37850
14    0.37850
15    0.36575
16    0.34475
17    0.30475
18    0.27875
19    0.26725
20    0.26475
21    0.30500
22    0.32775
23    0.37050
24    0.41550
25    0.46075
26    0.50675
27    0.52950
28    0.55525
29    0.59375
30    0.62025
31    0.61825
32    0.59525
33    0.56125
34    0.56725
35    0.60125
36    0.63600
37    0.67225
38    0.67375
39    0.65750
40    0.64525
41    0.62900
42    0.65850
43    0.70725
Name: exportacao_usd, dtype: float64

In [16]:
y_true = suino['exportacao_usd'].iloc[3:]
y_pred = sma.iloc[3:]
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
print(mae, rmse)

0.05490853658536585 0.06870222286672585

### Exponential Moving Average (EMA)

In [17]:
ema = suino['exportacao_usd'].ewm(span=4, adjust=False).mean()
print(ema)

0     0.260000
1     0.306000
2     0.343200
3     0.369920
4     0.300752
5     0.300451
6     0.327071
7     0.316642
8     0.288785
9     0.303671
10    0.339003
11    0.356602
12    0.359961
13    0.365577
14    0.376146
15    0.358488
16    0.327493
17    0.282096
18    0.284457
19    0.285074
20    0.279445
21    0.317667
22    0.342200
23    0.388120
24    0.413272
25    0.470363
26    0.507418
27    0.523651
28    0.535790
29    0.605474
30    0.630885
31    0.594531
32    0.541518
33    0.554511
34    0.609907
35    0.636344
36    0.622206
37    0.660924
38    0.676154
39    0.650093
40    0.610856
41    0.628113
42    0.703668
43    0.744601
Name: exportacao_usd, dtype: float64

In [18]:
y_true = suino['exportacao_usd'].iloc[3:]
y_pred = ema.iloc[3:]
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
print(mae, rmse)

0.04221491076013785 0.05113408305728897

## Baseline para frango

### Simple Moving Average (SMA)

In [19]:
sma = frango['exportacao_usd'].rolling(window=4).mean()
print(sma)

0         NaN
1         NaN
2         NaN
3     1.72275
4     1.69375
5     1.65550
6     1.62775
7     1.55700
8     1.54025
9     1.55450
10    1.51475
11    1.48625
12    1.56325
13    1.53975
14    1.57175
15    1.60650
16    1.57075
17    1.47150
18    1.47350
19    1.47075
20    1.45250
21    1.58525
22    1.57350
23    1.59625
24    1.62475
25    1.53925
26    1.44300
27    1.37075
28    1.34725
29    1.43400
30    1.58700
31    1.71250
32    1.81275
33    1.98725
34    2.09625
35    2.17500
36    2.30075
37    2.28125
38    2.23025
39    2.19825
40    2.10125
41    2.08125
42    2.13975
43    2.23175
Name: exportacao_usd, dtype: float64

In [20]:
y_true = frango['exportacao_usd'].iloc[3:]
y_pred = sma.iloc[3:]
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
print(mae, rmse)

0.1383048780487805 0.17212100465632438

### Exponential Moving Average (EMA)

In [21]:
ema = frango['exportacao_usd'].ewm(span=4, adjust=False).mean()
print(ema)

0     1.470000
1     1.587600
2     1.704960
3     1.733376
4     1.581626
5     1.593375
6     1.664025
7     1.595615
8     1.472169
9     1.550501
10    1.574701
11    1.496421
12    1.535852
13    1.551111
14    1.626267
15    1.582960
16    1.530576
17    1.389146
18    1.532287
19    1.522172
20    1.464903
21    1.562142
22    1.617285
23    1.609571
24    1.562943
25    1.484166
26    1.416499
27    1.373500
28    1.383700
29    1.515420
30    1.680052
31    1.732431
32    1.759459
33    2.020075
34    2.157245
35    2.144747
36    2.208048
37    2.258029
38    2.218417
39    2.130250
40    2.044150
41    2.127690
42    2.233814
43    2.286688
Name: exportacao_usd, dtype: float64

In [22]:
y_true = frango['exportacao_usd'].iloc[3:]
y_pred = ema.iloc[3:]
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
print(mae, rmse)

0.10883550761437485 0.1333947276579218